# src/Knarf/PlatformBundle/Resources/config/routing.yml

knarf_platform_home:
    path:      /{page}
    defaults: 
        _controller: KnarfPlatformBundle:Advert:index 
        page:    1
    requirements:
        page: \d*  

knarf_platform_view:
    path:      /advert/{id}
    defaults:
        _controller: KnarfPlatformBundle:Advert:view
    requirements:
        id: \d+

knarf_platform_add:
    path:      /ajout
    defaults: 
        _controller: KnarfPlatformBundle:Advert:add
        
knarf_platform_edit:
    path:      /edit/{id}
    defaults:
        _controller: KnarfPlatformBundle:Advert:edit
    requirements:
        id: \d+    

knarf_platform_delete:
    path:      /delete/{id}
    defaults:
        _controller: KnarfPlatformBundle:Advert:delete
    requirements:
        id: \d+

