services:
#    knarf_platform.example:
#        class: Knarf\PlatformBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
        # Fixtures services
#        Knarf\PlatformBundle\DataFixtures\ORM\AdvertsFixture:
#            tags: [doctrine.fixture.orm]
#        
#        Knarf\PlatformBundle\DataFixtures\ORM\UserFixtures:
#            arguments: ["@security.password_encoder"]
#            tags: [doctrine.fixture.orm]
#            
#        Knarf\PlatformBundle\DataFixtures\ORM\RubriqueFixtures:
#            tags: [doctrine.fixture.orm]