services:
#    knarf_platform.example:
#        class: Knarf\PlatformBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
        knarf_advert_subscriber.listener:
            class: Knarf\PlatformBundle\Events\AdvertSubscriber
            arguments: [ "@vich_uploader.templating.helper.uploader_helper" ]
            tags:
                - { name: jms_serializer.event_subscriber }
