## YAML Template.
---
commentaire_home:
    path:     /
    defaults: 
        _controller: KnarfPlatformBundle:Commentaire:index
  
commentaire_add:
    path:   /ajout
    defaults:
        _controller: KnarfPlatformBundle:Commentaire:add
        
commentaire_edit:
    path:   /edit/{id}
    defaults:
        _controller: KnarfPlatformBundle:Commentaire:edit
    requirements:
        id: \d+
        
commentaire_delete:
    path: /delete/{id}
    defaults:
        _controller: KnarfPlatformBundle:Commentaire:delete
    requirements:
        id: \d+
        
commentaire_view:
    path:      /{id}
    defaults:
        _controller: KnarfPlatformBundle:Commentaire:view
    requirements:
        id: \d+

