## YAML Template.
---
rubrique_ext_index:
    path: /
    defaults:
        _controller: KnarfPlatformBundle:Rubrique:extendedIndex

rubrique_home:
    path:     /
    defaults: 
        _controller: KnarfPlatformBundle:Rubrique:index
  
rubrique_ajout:
    path:   /ajout
    defaults:
        _controller: KnarfPlatformBundle:Rubrique:add
        
rubrique_edit:
    path:   /edit/{slug}
    defaults:
        _controller: KnarfPlatformBundle:Rubrique:edit
        
rubrique_delete:
    path: /delete/{slug}
    defaults:
        _controller: KnarfPlatformBundle:Rubrique:delete
    requirements:
        
rubrique_ext:
    path:   /{slug}
    defaults:
        _controller: KnarfPlatformBundle:Rubrique:extended

rubrique_view:
    path:      /{slug}
    defaults:
        _controller: KnarfPlatformBundle:Rubrique:view
        


