<?php

namespace Knarf\PlatformBundle\Repository;


use Doctrine\ORM\QueryBuilder;

/**
 * AdvertRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdvertRepository extends \Doctrine\ORM\EntityRepository
{
    public function afficherDerniersArticles()
    {
        $qb = $this->createQueryBuilder('a')
               // ->where('a.published = ?1')
                ->addOrderBy('a.date', 'DESC');
        
        return $qb->getQuery()->getResult();
    }
}
