<?php

namespace Knarf\PlatformBundle\Repository;

/**
 * CommentaireRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentaireRepository extends \Doctrine\ORM\EntityRepository
{
        public function afficherCommentairesAnnonce($advertId)
    {
        $qb = $this->createQueryBuilder('c')
                ->join('c.advert', 'a')
                ->where('a.id = :id')
                ->setParameter('id', $advertId)
                ->addOrderBy('c.datePublication', 'DESC');
        
        return $qb->getQuery()->getResult();
    }
}
