<?php

namespace Knarf\PlatformBundle\Repository;

use Doctrine\ORM\QueryBuilder;
use Knarf\CoreBundle\Repository\AbstractGenericRepository;
use Knarf\PlatformBundle\Entity\Rubrique;
use Knarf\PlatformBundle\Repository\Interfaces\AdvertRepositoryInterface;

/**
 * RubriqueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RubriqueRepository extends AbstractGenericRepository 
{
    public function getRubriques() 
    {
        $qb = $this->createQueryBuilder('r')
        ->addOrderBy('r.intitule', 'ASC');
        
        return $qb->getQuery()->getResult();
    }
    
    public function getRubriquesEtAdverts()
    {
        $qb = $this->getEntityManager()->createQueryBuilder();
        $results = $qb->select('r', 'a')
                ->from('KnarfPlatformBundle:Rubrique', 'r')
                ->join('r.adverts', 'a')
                ->where('a.published = :published')
                //->andWhere('a.date')
                ->setParameter('published', true)
                ->orderBy('a.date', 'DESC')
                //->setMaxResults(6)
                ->getQuery()
                ->getResult()
                ;
        return $results;
    }    




}
