<?php

namespace Knarf\PlatformBundle\Repository;


use Knarf\CoreBundle\Repository\AbstractGenericRepository;

/**
 * VoteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VoteRepository extends AbstractGenericRepository
{
    
}
