<?php

namespace Knarf\UserBundle\Repository;
use Doctrine\ORM\Query;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
    public function mettreProfilAJour($userId)
    {
        $query = $this->createQuery(
                'UPDATE Knarf\UserBundle\Entity\User u SET u.nom_image'
                );
    }
    
}
