imports:
    - { resource: config.yml }

#doctrine:
#    orm:
#        metadata_cache_driver: apc
#        result_cache_driver: apc
#        query_cache_driver: apc
doctrine:
    dbal:
        url: "%env(DATABASE_URL)"
monolog:
    handlers:
        main:
            type:           rotating_file
            max_files:      3
            path:           "php://stderr"
            level:          info
            channels:       ['!doctrine', '!security']
        doctrine:
            type:           stream
            path:           "php://stderr"
            channels:       doctrine
        authentication:
            type:           rotating_file
            max_files:      15
            path:           "php://stderr"
            level:          info
            channels:       security #mywebsite_user    
        nested:
            type: stream
            path: "php://stderr"
            level: debug
        console:
            type: console
            process_psr_3_messages: false
