imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: validator.yml }
    - { resource: mail_blacklist.yml }
    - { resource: "@KnarfCoreBundle/Resources/config/services.yml" }
    - { resource: user/authentication.yml }
    - { resource: user/form.xml }
    - { resource: user/manager.xml }
    - { resource: user/repository.xml }
    - { resource: user/listener.xml }
    - { resource: user/handler.xml }

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: fr

framework:
    #esi: ~
    translator: { fallbacks: ['%locale%'] }
    secret: '%secret%'
    router:
        resource: '%kernel.project_dir%/app/config/routing.yml'
        strict_requirements: ~
    form: true
    csrf_protection: true
    validation: { enable_annotations: true }
    serializer: { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale: '%locale%'
    trusted_hosts: ~
    session:
        # https://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id: session.handler.native_file
        save_path: '%kernel.project_dir%/var/sessions/%kernel.environment%'
        cookie_lifetime: 3600
        gc_maxlifetime: 1800
    fragments: ~
    http_method_override: true
    assets: ~
    php_errors:
        log: true

# Twig Configuration
twig:
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    form_themes:
        - 'bootstrap_3_layout.html.twig'
    globals:
        website: mywebsite    

# Doctrine Configuration
doctrine:
    dbal:
        driver: pdo_mysql
        host: '%database_host%'
        port: '%database_port%'
        dbname: '%database_name%'
        user: '%database_user%'
        password: '%database_password%'
        charset: UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.project_dir%/var/data/data.sqlite"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #path: '%database_path%'

    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: '%mailer_transport%'
    host: '%mailer_host%'
    username: '%mailer_user%'
    password: '%mailer_password%'
    spool: { type: memory }
    encryption: '%mailer_encryption%'
    port: '%mailer_port%'
    auth_mode: '%mailer_auth_mode%'

# OneUpFlysytemBundle Configuration
oneup_flysystem:
    adapters:
        upload_adapter:
            local:
                directory: '%kernel.root_dir%/../web/uploads'
    filesystems:
        upload_image_fs:
            adapter:   upload_adapter
            mount:  upload_image_fs      
                       
# VichUploaderBundle Configuration
vich_uploader:
    db-driver: orm    
    #storage: file_system
    mappings:
       upload_media:
        uri_prefix: /uploads
        upload_destination: '%kernel.root_dir%/../web/uploads/'
        inject_on_load: true
        delete_on_update: true
        delete_on_remove: true
    
# LiipImagineBundle Configuration
liip_imagine:
    resolvers:
       default:
         web_path: ~
      
    filter_sets:        
        my_thumb:
            quality: 85
            filters:
                thumbnail: { size: [50, 50], mode: outbound }
        my_thumb_resize:
            quality: 50
            cache: false
            filters:
                thumbnail: { size: [120, 120], mode: outbound }
                relative_resize: { heighten: 78 }

# Assetic Configuration
assetic:
    debug:          '%kernel.debug%'
    use_controller: '%kernel.debug%'
    filters:
        cssrewrite: ~
        
# Fos_Rest Configuration
fos_rest:
    body_listener:
       decoders:
           json: fos_rest.decoder.json
    format_listener:
        rules:
            - { path: '^/api', priorities: ['json'], fallback_format: 'json' }
            - { path: '^/', priorities: ['html'], fallback_format: 'html'}
    param_fetcher_listener: true
    view:
        view_response_listener: true
        formats:
            xml: true
            json: true
            jsonp: true
        templating_formats:
            html: true
        force_redirects:
            html: true
        failed_validation: HTTP_BAD_REQUEST
      #default_engine: twig
        mime_types:
            json : ['application/json']
    routing_loader:
        include_format: false
    access_denied_listener:
        json: true
        xml: true
        html: true
    exception:
        codes:
            'Symfony\Component\Routing\Exception\ResourceNotFoundException': 404
            'Doctrine\ORM\OptimisticLockException': HTTP_CONFLICT
        messages:
            'Symfony\Component\Routing\Exception\ResourceNotFoundException': true      
      
    service:
        router: router
        templating: templating
        view_handler: fos_rest.view_handler.default    
    
stof_doctrine_extensions:
    default_locale: fr_FR
    orm:
        default:
            timestampable: true
            sluggable: true
    
