imports:
    - { resource: config.yml }

#doctrine:
#    orm:
#        metadata_cache_driver: apc
#        result_cache_driver: apc
#        query_cache_driver: apc

monolog:
    handlers:
        main:
            type:           rotating_file
            max_files:      3
            path:           "%kernel.logs_dir%/%kernel.environment%.all.log"
            level:          info
            channels:       ['!doctrine', '!security']
        doctrine:
            type:           stream
            path:           "%kernel.logs_dir%/%kernel.environment%.doctrine.log"
            channels:       doctrine
        authentication:
            type:           rotating_file
            max_files:      15
            path:           "%kernel.logs_dir%/%kernel.environment%.auth.log"
            level:          info
            channels:       security #mywebsite_user    
        nested:
            type: stream
            path: '%kernel.logs_dir%/%kernel.environment%.log'
            level: debug
        console:
            type: console
            process_psr_3_messages: false
