imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: validator.yml }
    - { resource: mail_blacklist.yml }
#    - { resource: repository.yml }
#    - { resource: manager.yml }
    - { resource: "@KnarfCoreBundle/Resources/config/services.yml" }
    - { resource: "@KnarfCoreBundle/Resources/config/validator.yml" }
    - { resource: user/authentication.yml }
    - { resource: user/form.xml }
    - { resource: user/manager.xml }
    - { resource: user/repository.xml }
    - { resource: user/listener.xml }
    - { resource: user/handler.xml }

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: fr

framework:
    #esi: ~
    translator: { fallbacks: ['%locale%'] }
    secret: '%secret%'
    router:
        resource: '%kernel.project_dir%/app/config/routing.yml'
        strict_requirements: ~
    form: true
    csrf_protection: true
    validation: { enable_annotations: true }
    serializer: { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale: '%locale%'
    trusted_hosts: ~
    session:
        # https://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id: session.handler.native_file
        save_path: '%kernel.project_dir%/var/sessions/%kernel.environment%'
        cookie_lifetime: 7200
        gc_maxlifetime: 3600
    fragments: ~
    http_method_override: true
    assets: ~
    php_errors:
        log: true

# Twig Configuration
twig:
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    form_themes:        
        - 'bootstrap_3_layout.html.twig'        
        - 'VichUploaderBundle:Form:fields.html.twig'
        - '@FOSCKEditor/Form/ckeditor_widget.html.twig'
        - 'GoogleMapsBundle:Form:google_maps_layout.html.twig'
    globals:
        website:     

# Doctrine Configuration
doctrine:
    dbal:
        default_connection: default
        connections:
           #Mysql
           default:
                driver:   pdo_mysql
                host:     "%database_host%"
                port:     "%database_port%"
                dbname:   "%database_name%"
                user:     "%database_user%"
                password: "%database_password%"
                charset:  UTF8
           #Postgresql
           pgsql:
                driver:   pdo_pgsql
                host:     "%psql_database_host%"
                port:     "%psql_database_port%"
                dbname:   "%psql_database_name%"
                user:     "%psql_database_user%"
                password: "%psql_database_password%"
                charset:  UTF8


    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: '%mailer_transport%'
    host: '%mailer_host%'
    username: '%mailer_user%'
    password: '%mailer_password%'
    spool: { type: memory }
    encryption: '%mailer_encryption%'
    port: '%mailer_port%'
    auth_mode: '%mailer_auth_mode%'

# OneUpFlysystemBundle Configuration
oneup_flysystem:
    adapters:
        upload_adapter:
            local:
                directory: '%kernel.root_dir%/../web/uploads'
    filesystems:
        upload_image_fs:
            adapter:   upload_adapter
            mount:  upload_image_fs      
                       
# VichUploaderBundle Configuration
vich_uploader:
    db-driver: orm    
    #storage: file_system
    mappings:
       upload_media:
        uri_prefix: /uploads/medias
        upload_destination: '%kernel.root_dir%/../web/uploads/medias'
        namer: vich_uploader.namer_origname
        inject_on_load: true
        delete_on_update: true
        delete_on_remove: true
       upload_avatar:
         uri_prefix: /uploads/avatars
         upload_destination: '%kernel.root_dir%/../web/uploads/avatars/'
         namer: vich_uploader.namer_origname
         inject_on_load: true
         delete_on_update: true
         delete_on_remove: true           
           
    
# LiipImagineBundle Configuration
liip_imagine:
    resolvers:
        default:
            web_path:
                web_root: '%kernel.project_dir%/web'
                cache_prefix: 'media/cache'            
    loaders:
        default:
            filesystem:
                data_root:
                    - '%kernel.root_dir%/../web/'
    driver: gd  
    filter_sets:
        article_thumb:
            quality: 100
            filters:
                relative_resize:
                    heighten: 200

        my_thumb:
            #data_loader: avatar
            quality: 100
            filters:                
                auto_rotate: true
                thumbnail: { size: [48, 48], mode: inset }
        my_thumb_resize:            
            #data_loader: avatar
            quality: 100
            cache: false
            filters:
                auto_rotate: true
                downscale:
                    max: [ 390, 550 ]
        
# Fos_Rest Configuration
fos_rest:
    body_listener:
       decoders:
           json: fos_rest.decoder.json
    format_listener:
        rules:
            - { path: '^/api', priorities: ['json'], fallback_format: 'json' }
            - { path: '^/create-client', priorities: ['json'], fallback_format: 'json' }
            - { path: '^/', priorities: ['html'], fallback_format: 'html'}
    param_fetcher_listener: true
    view:
        view_response_listener: true
        formats:
            xml: true
            json: true
            jsonp: true
        templating_formats:
            html: true
#        force_redirects:
#            html: true
        failed_validation: HTTP_BAD_REQUEST
      #default_engine: twig
        mime_types:
            json : ['application/json']
    routing_loader:
        #default_format: json
        include_format: false
    access_denied_listener:
        json: true
        xml: true
        html: true
    exception:
        codes:
            'Symfony\Component\Routing\Exception\ResourceNotFoundException': 404
            'Doctrine\ORM\OptimisticLockException': HTTP_CONFLICT
        messages:
            'Symfony\Component\Routing\Exception\ResourceNotFoundException': true
    service:
        router: router
        templating: templating
        view_handler: fos_rest.view_handler.default    
    
#fos_oauth
fos_oauth_server:
    db_driver: orm       
    client_class:        Knarf\ApiBundle\Entity\Client
    access_token_class:  Knarf\ApiBundle\Entity\AccessToken
    refresh_token_class: Knarf\ApiBundle\Entity\RefreshToken
    auth_code_class:     Knarf\ApiBundle\Entity\AuthCode
    service:
        user_provider: security.user.provider.concrete.database_users
        options:
                access_token_lifetime: 86400
                refresh_token_lifetime: 1209600
                auth_code_lifetime: 30
                supported_scopes: user   

stof_doctrine_extensions:
    default_locale: fr_FR
    orm:
        default:
            timestampable: true
            sluggable: true
        pgsql:
            timestampable: true
            sluggable: true
            
fos_ck_editor:
    base_path: "build/ckeditor"
    js_path:   "build/ckeditor/ckeditor.js"
    inline: false
    filebrowsers:
        - VideoBrowse
        - VideoUpload
    configs:
        full_config:
            jquery: true
            enterMode: CKEDITOR.ENTER_P
            height: '400px'
            language: '%locale%'
            #toolbar: standard
#            filebrowserBrowseRoute: elfinder
#            filebrowserBrowseRouteParameters: []
            extraPlugins: ['youtube', 'image2', 'imageresponsive', 'html5video', 'html5audio']
            removePlugins: 'image'
            uiColor: '#cccccc'
            imageUploadUrl: '/web/uploads/medias'
            image2_disableResizer: false
        basic_config:
            jquery: true
            heihgt: '250px'
            language: '%locale%'
            toolbar: basic
            enterMode: CKEDITOR.ENTER_P
        plugins:
            youtube:
                path: '/web/build/fosckeditor/plugins/youtube/'
                filename: 'plugin.js'
           
nelmio_api_doc:
    sandbox:
        authentication:
            name: access_token
            delivery: query
            type: bearer

            custom_endpoint: false
        enabled:  true
        
knp_paginator:
    page_range: 5
    default_options:
        page_name: page                
        sort_field_name: sort          
        sort_direction_name: direction
        distinct: false                 
    template:
        pagination: 'KnpPaginatorBundle:Pagination:twitter_bootstrap_v3_pagination.html.twig'
        sortable: '@KnpPaginator/Pagination/sortable_link.html.twig'
        filtration: '@KnpPaginator/Pagination/filtration.html.twig'

fos_comment:
    db_driver: orm
    class:
        model:
            comment: Knarf\PlatformBundle\Entity\Commentaire
            thread: Knarf\PlatformBundle\Entity\Thread
            vote: Knarf\PlatformBundle\Entity\Vote
    acl: true
    service:
        acl:
            thread:  fos_comment.acl.thread.roles
            comment: knarf.platformbundle.acl.comment.roles
            vote:    fos_comment.acl.vote.roles
#        manager:
#            thread:  fos_comment.manager.thread.acl
#            comment: fos_comment.manager.comment.acl
#            vote:    fos_comment.manager.vote.acl
    acl_roles:
        comment:
            create: ROLE_USER
            view: IS_AUTHENTICATED_ANONYMOUSLY
            edit: ROLE_USER
            delete: ROLE_USER
        thread:
            create: ROLE_USER
            view: IS_AUTHENTICATED_ANONYMOUSLY
            edit: ROLE_ADMIN
            delete: ROLE_ADMIN
        vote:
            create: ROLE_USER
            view: IS_AUTHENTICATED_ANONYMOUSLY
            edit: ROLE_USER
            delete: ROLE_USER
            
google_maps:
    api_key: 'AIzaSyA2K-avkDmpftUPLab9r9oqBca8vjM1-i4'
    
lexik_jwt_authentication:
    secret_key:       '%kernel.project_dir%/config/jwt/private.pem' # required for token creation
    public_key:       '%kernel.project_dir%/config/jwt/public.pem'  # required for token verification
    pass_phrase:      'Equaled42blomberg04glances' # required for token creation, usage of an environment variable is recommended
    token_ttl:        3600    
    
webpack_encore:
    output_path: "%kernel.root_dir%/../web/build/"
