services:
    app.advert.manager:
        class: Knarf\PlatformBundle\Entity\Manager\AdvertManager
        arguments: ["@app.advert.repository"]
#        calls:
#            - [setFormFactory, ['@form.factory]]
#            - [setRouter, ['@router']]            
#            - [setSearchFormType, ['KnarfPlatformBundle\Form\Type\AdvertFilterType']]
        lazy: true
        tags:
            - { name: app.manager_service }
