services:
    app.advert.repository:
        class: Knarf\PlatFormBundle\Repository\AdvertRepository
        factory: ["@doctrine.orm.default_entity_manager", getRepository]
        arguments: ['Knarf\PlatformBundle\Entity\Advert']
        lazy: true