knarf_api:
    resource: "@KnarfApiBundle/Resources/config/routing.yml"
    prefix:   /api
    type: rest
    
knarf_user:
    resource: "@KnarfUserBundle/Controller/"
    type: annotation
    prefix: /   

knarf_platform:
    resource: "@KnarfPlatformBundle/Controller/"
    type: annotation
    prefix:   /
    
registration:
    path: /activate
    defaults:
        _controller: KnarfUserBundle:Register:activate

commentaire:
    resource: "@KnarfPlatformBundle/Resources/config/routing/commentaire.yml"
    prefix: /commentaire
        
_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"
    
contact:
    path: /contact
    defaults:
        _controller: KnarfPlatformBundle:Contact:contact
        
nelmio-api-doc:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /documentation
    
fos_oauth_server_token:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/token.xml"

fos_oauth_server_authorize:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/authorize.xml"
    
oauth_server_auth_login:
    path:  /oauth/v2/auth_login
    defaults: { _controller: KnarfUserBundle:Security:login }

oauth_server_auth_login_check:
    path:  /oauth/v2/auth_login_check
    defaults: { _controller: KnarfUserBundle:Security:loginCheck }
    
fos_comment_api:
    type: rest
    resource: "@FOSCommentBundle/Resources/config/routing.yml"
    prefix: /comment/api
    defaults: { _format: html }    



        
        
        
