knarf_core:
    resource: "@KnarfCoreBundle/Controller/"
    type:     annotation
    prefix:   /

knarf_api:
    resource: "@KnarfApiBundle/Resources/config/routing.yml"
    prefix:   /api
    type: rest
    
knarf_user:
    resource: "@KnarfUserBundle/Controller/"
    type: annotation
    prefix: /

knarf_platform:
    resource: "@KnarfPlatformBundle/Resources/config/routing.yml"
    prefix:   /
    
rubrique:
    resource: "@KnarfPlatformBundle/Resources/config/routing/rubrique.yml"
    prefix: /rubrique

commentaire:
    resource: "@KnarfPlatformBundle/Resources/config/routing/commentaire.yml"
    prefix: /commentaire
        
profile:
    path: /profile/
    defaults:
        _controller: KnarfUserBundle:Security:profile
        
change_email:
    path: /profile/change-email
    defaults:
        _controller: KnarfUserBundle:UpdateProfile:editEmail
        
profile_view:
    path: /member/{id}
    defaults:
        _controller: KnarfUserBundle:Security:viewMember
    requirements:
        id: \d+    

change_image:
    path: /profile/change-image
    defaults:
        _controller: KnarfUserBundle:UpdateProfile:editImage
        
admin:
    path: /admin
    defaults:
        _controller: KnarfUserBundle:Security:admin
        
registration:
    path: /activate
    defaults:
        _controller: KnarfUserBundle:Register:activate
        
_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"
    
contact:
    path: /contact
    defaults:
        _controller: KnarfPlatformBundle:Contact:contact
        
nelmio-api-doc:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /documentation
        


        
        
        
