
knarf_platform:
    resource: "@KnarfPlatformBundle/Resources/config/routing.yml"
    prefix:   /
    
rubrique:
    resource: "@KnarfPlatformBundle/Resources/config/routing/rubrique.yml"
    prefix: /rubrique

commentaire:
    resource: "@KnarfPlatformBundle/Resources/config/routing/commentaire.yml"
    prefix: /commentaire

login:
    path: /login
    defaults:
        _controller: KnarfUserBundle:Security:login

login_check:
    path: /login_check

logout:
    path: /logout
    
register:
    path: /register
    defaults:
        _controller: KnarfUserBundle:Security:register
        
profile:
    path: /profile/
    defaults:
        _controller: KnarfUserBundle:Security:profile
        
profile_edit:
    path: /profile/edit
    defaults:
        _controller: KnarfUserBundle:Security:editProfile
        
profile_view:
    path: /member/{id}
    defaults:
        _controller: KnarfUserBundle:Security:viewMember
    requirements:
        id: \d+    
        
admin:
    path: /admin
    defaults:
        _controller: KnarfUserBundle:Security:admin
        
_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"
