knarf_api:
    resource: "@KnarfApiBundle/Resources/config/routing.yml"
    prefix:   /api
    type: rest
    
knarf_user:
    resource: "@KnarfUserBundle/Controller/"
    type: annotation
    prefix: /   

knarf_platform:
    resource: "@KnarfPlatformBundle/Controller/"
    type: annotation
    prefix:   /
    
registration:
    path: /activate
    defaults:
        _controller: KnarfUserBundle:Register:activate
    
rubrique:
    resource: "@KnarfPlatformBundle/Resources/config/routing/rubrique.yml"
    prefix: /rubrique

commentaire:
    resource: "@KnarfPlatformBundle/Resources/config/routing/commentaire.yml"
    prefix: /commentaire
        
_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"
    
contact:
    path: /contact
    defaults:
        _controller: KnarfPlatformBundle:Contact:contact
        
nelmio-api-doc:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /documentation
        


        
        
        
