# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    encoders:
        Symfony\Component\Security\Core\User\User: bcrypt
        Knarf\UserBundle\Entity\User: bcrypt

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]
        
    providers:
        main:
            entity:
                class:      KnarfUserBundle:User
       

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false     

            
        main:
            pattern: ^/
            anonymous: true
            # activate different ways to authenticate

            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            #http_basic: ~

            # https://symfony.com/doc/current/security/form_login_setup.html
            provider: main
            form_login:
              login_path: login
              check_path: login_check
              default_target_path: profile
              csrf_token_generator: security.csrf.token_manager
            logout_on_user_change: true
            remember_me:
                secret: '%secret%'
                lifetime: 604800
                path: /
                #always_remember_me: true
            logout:
                path: /logout
                target: /
                invalidate_session: false
                handlers: [logout_listener]


    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/profile, roles: ROLE_USER }
        - { path: ^/rubrique/delete, roles: ROLE_ADMIN }
        - { path: ^/rubrique/edit, roles: ROLE_ADMIN }
        - { path: ^/rubrique/ajout, roles: ROLE_ADMIN }
        - { path: ^/login | register, roles: IS_AUTHENTICATED_ANONYMOUSLY }