# Learn more about services, parameters and containers at
# https://symfony.com/doc/current/service_container.html
parameters:
    admin_pass: 'secret_password'

services:
    # default configuration for services in *this* file
    _defaults:
        # automatically injects dependencies in your services
        autowire: true
        # automatically registers your services as commands, event subscribers, etc.
        autoconfigure: true
        # this means you cannot fetch services directly from the container via $container->get()
        # if you need to do this, you can override this setting on individual services
        public: false
        bind:
            $adminPass: '%admin_pass%'
    
    Knarf\UserBundle\:
        resource: '../../src/Knarf/UserBundle/*'
        exclude: '../../src/Knarf/UserBundle/{Entity,Repository,DependencyInjection}'
        
    Knarf\PlatformBundle\:
        resource: '../../src/Knarf/PlatformBundle/*'
        # you can exclude directories or files
        # but if a service is unused, it's removed anyway
        exclude: '../../src/Knarf/PlatformBundle/{Entity,Repository,DependencyInjection}'

    Knarf\ApiBundle\:
        resource: '../../src/Knarf/ApiBundle/*'
        # you can exclude directories or files
        # but if a service is unused, it's removed anyway
        exclude: '../../src/Knarf/ApiBundle/{Entity,Repository}'
    
    Knarf\PlatformBundle\Controller\:
        resource: '../../src/Knarf/PlatformBundle/Controller'
        tags: ['controller.service_arguments']
        
    Knarf\ApiBundle\Controller\:
        resource: '../../src/Knarf/ApiBundle/Controller'
        tags: ['controller.service_arguments'] 
            
    
    Knarf\PlatformBundle\Service\MercureCookieGenerator:
            arguments:
                $secret: '%secret%'
    
    Knarf\PlatformBundle\Mercure\JwtProvider:
            arguments:
                $secret: '%secret%' 
    
    Knarf\PlatformBundle\DataFixtures\ORM\MediaFixtures:
        tags: [doctrine.fixture.orm]
    
    Knarf\PlatformBundle\DataFixtures\ORM\AdvertsFixture:
           tags: [doctrine.fixture.orm]
       
    Knarf\PlatformBundle\DataFixtures\ORM\UserFixtures:
           arguments: ["@security.password_encoder"]
           tags: [doctrine.fixture.orm]
           
    Knarf\PlatformBundle\DataFixtures\ORM\RubriqueFixtures:
           tags: [doctrine.fixture.orm]
    
    Knarf\UserBundle\Services\SendMailToNeverConnectedUserService:
        arguments:
            $template: 'KnarfUserBundle:Security:login_invite_mail.html.twig'
            $from: '%email_from%'
            
    Knarf\UserBundle\Services\SendMailToOldConnectedUserService:
        arguments:
            $template: 'KnarfUserBundle:Security:login_invite_mail2.html.twig'
            $from: '%email_from%'
            
    Knarf\UserBundle\Services\SendMailToNotActiveUserService:
        arguments:
            $template: 'KnarfUserBundle:Security:email_not_active.html.twig'
            $from: '%email_from%'
            
    vich_uploader.namer_origname.upload_media:
        class: Vich\UploaderBundle\Naming\OrignameNamer
        public: true
    
    vich_uploader.namer_origname.upload_avatar:
        class: Vich\UploaderBundle\Naming\OrignameNamer
        public: true
        
    Knarf\PlatformBundle\Listeners\MediaListener:
            arguments: ["@liip_imagine.cache.manager", "@vich_uploader.templating.helper.uploader_helper"]
            tags:
                - { name: doctrine.event_listener, event: postUpdate }
                - { name: doctrine.event_listener, event: preRemove }
                - { name: kernel.event_listener, event: vich_uploader.pre_remove}
    
    Knarf\PlatformBundle\Subscriber\MediaSubscriber:
            arguments: [ "@liip_imagine.cache.manager", "@vich_uploader.templating.helper.uploader_helper" ]
            tags:
                - { name: jms_serializer.event_subscriber }
        
        # Acl Comment Role
    knarf.platformbundle.acl.comment.roles:
        class: Knarf\PlatformBundle\Acl\RoleCommentAcl
        arguments:
            - "@security.authorization_checker"
            - "@security.token_storage"
            - IS_AUTHENTICATED_REMEMBERED
            - IS_AUTHENTICATED_ANONYMOUSLY
            - ROLE_USER
            - ROLE_USER
            - "%fos_comment.model.comment.class%"
            
    knarf.ajax.authentication.listener:
     class: Knarf\UserBundle\Listeners\AjaxAuthenticationListener
     tags:
        - { name: kernel.event_listener, event: kernel.exception, method: onCoreException, priority: 1000 }
    
    Knarf\PlatformBundle\Subscriber\PaginateDirectorySubscriber:
        tags:
            - { name: knp_paginator.subscriber }
