# Learn more about services, parameters and containers at
# https://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    # default configuration for services in *this* file
    _defaults:
        # automatically injects dependencies in your services
        autowire: true
        # automatically registers your services as commands, event subscribers, etc.
        autoconfigure: true
        # this means you cannot fetch services directly from the container via $container->get()
        # if you need to do this, you can override this setting on individual services
        public: false
    

    vich_uploader.namer_origname.upload_media:
        class: Vich\UploaderBundle\Naming\OrignameNamer
        public: true
    
    vich_uploader.namer_origname.upload_avatar:
        class: Vich\UploaderBundle\Naming\OrignameNamer
        public: true
        
    knarf_advert_subscriber.listener:
        class: Knarf\PlatformBundle\Events\AdvertSubscriber
        arguments: [ "@vich_uploader.templating.helper.uploader_helper" ]
        tags:
            - { name: jms_serializer.event_subscriber }
        
        # Acl Comment Role
    knarf.platformbundle.acl.comment.roles:
        class: Knarf\PlatformBundle\Acl\RoleCommentAcl
        arguments:
            - "@security.authorization_checker"
            - "@security.token_storage"
            - IS_AUTHENTICATED_REMEMBERED
            - IS_AUTHENTICATED_ANONYMOUSLY
            - ROLE_USER
            - ROLE_USER
            - "%fos_comment.model.comment.class%"     