## src/Knarf/UserBundle/Resources/config/serializer/Entity.User.yml
Knarf\UserBundle\Entity\User:
    exclusion_policy: none
    properties:
        id:
            groups: ['user', 'advert', 'commentaire']
        username:
            groups: ['user', 'advert', 'commentaire']
        email:
            groups: ['user', 'advert', 'commentaire']
        createdAt:  
            groups: ['user', 'advert', 'commentaire']
        updatedAt:
            groups: ['user', 'advert', 'commentaire']
        lastTimeConnect:
            groups: ['user', 'advert', 'commentaire']
        avatar:
            groups: ['user']
        adverts:
            groups: ['user']
        commentaires:
            groups: ['user']