## src/Knarf/UserBundle/Resources/config/serializer/Entity.Avatar.yml
Knarf\UserBundle\Entity\Avatar:
    exclusion_policy: none
    properties:
        id:
            groups: ['user', 'avatar']
        nomMedia:            
            groups: ['user', 'avatar']        
        date:            
            groups: ['user', 'avatar']        
        user:
            groups: ['avatar']
        