# src/Knarf/ApiBundle/Resources/config/serialization.yml

Knarf\UserBundle\Entity\App_User:
    attributes:
        id:
            groups: ['user', 'advert', 'commentaire']
        username:
            groups: ['user', 'advert', 'commentaire']
        email:
            groups: ['user', 'advert', 'commentaire']
        createdAt:  
            groups: ['user', 'advert', 'commentaire']
        updatedAt:
            groups: ['user', 'advert', 'commentaire']
        lastTimeConnect:
            groups: ['user', 'advert', 'commentaire']
        nomMedia:
            groups: ['user', 'advert', 'commentaire']
        adverts:
            groups: ['user']
        commentaires:
            groups: ['user']
            
Knarf\PlatformBundle\Entity\Advert:
    attributes:
        id:
            groups: ['user', 'advert', 'commentaire', 'rubrique']
        
        title:
            groups: ['user', 'advert', 'commentaire', 'rubrique']
            
        content:
            groups: ['user', 'advert', 'commentaire', 'rubrique']
        
        date:
            groups: ['user', 'advert', 'commentaire', 'rubrique']
            
        updateAt:
            groups: ['user', 'advert', 'commentaire', 'rubrique']
            
        nomMedia:
            groups: ['user', 'advert', 'commentaire', 'rubrique']         
                
            
        user:
            groups: ['advert']
            
        rubrique:
            groups: ['advert']
            
        commentaires:
            groups: ['advert']
            
Knarf\PlatformBundle\Entity\Rubrique:
    attributes:
        id:
            groups: ['advert', 'rubrique']
            
        intitule:
            groups: ['advert', 'rubrique']
            
        image:
            groups: ['advert', 'rubrique']
            
        adverts:
            groups: ['rubrique']
            
            
Knarf\PlatformBundle\Entity\Commentaire:
    attributes:
        id:
            groups: ['advert', 'user', 'commentaire']
            
        contenu:
            groups: ['advert', 'user', 'commentaire']
            
        advert:
            groups: ['commentaire']
            
        user:
            groups: ['commentaire']
