## src/Knarf/PlatformBundle/Resources/config/serializer/Entity.Advert.yml
Knarf\PlatformBundle\Entity\Advert:
    exclusion_policy: none
    properties:
        id:
            groups: ['app_user', 'advert', 'commentaire', 'media']
        
        title:
            groups: ['app_user', 'advert', 'commentaire', 'media']
            
        content:
            groups: ['app_user', 'advert', 'commentaire', 'media']
        
        date:
            groups: ['app_user', 'advert', 'commentaire', 'media']
            
        updateAt:
            groups: ['app_user', 'advert', 'commentaire', 'media']          
               
                
            
        media:
            groups: ['advert']
        app_user:
            groups: ['advert']
            
        rubrique:
            groups: ['advert']
            
        commentaires:
            groups: ['advert']
