## src/Knarf/PlatformBundle/Resources/config/serializer/Entity.Advert.yml
Knarf\PlatformBundle\Entity\Advert:
    exclusion_policy: none
    properties:
        id:
            groups: ['user', 'advert', 'commentaire', 'rubrique']
        
        title:
            groups: ['user', 'advert', 'commentaire', 'rubrique']
            
        content:
            groups: ['user', 'advert', 'commentaire', 'rubrique']
        
        date:
            groups: ['user', 'advert', 'commentaire', 'rubrique']
            
        updateAt:
            groups: ['user', 'advert', 'commentaire', 'rubrique']          
               
                
            
        user:
            groups: ['advert']
            
        rubrique:
            groups: ['advert']
            
        commentaires:
            groups: ['advert']
